[metadata.heroku]
  root-package = "github.com/heroku/go-getting-started"
  go-version = "1.8.3"
  install = [ "./..." ]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.10"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.6.2"
